name: Bev A. Dransfeldt
description: Music \| Events \| Marketing
url:
baseurl: ""
permalink: /:title/
favicon: /assets/img/favicon.ico
social_image: /assets/img/social-image.png
analytics_id: UA-144722711-1
kramdown:
  input: GFM
sass:
  sass_dir: assets/partials
  style: compressed
plugins:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME